from __future__ import annotations

"""Build lightweight feature tables for fast LDA/PCA/theta-regression iteration.

Inputs are the existing wide threshold population CSV and unit summary generated by
Threshold_LDA_TuningWN_pre.py. Outputs are written under ../derived by default.
"""

import argparse
import json
import math
import time
from pathlib import Path

import numpy as np
import pandas as pd


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
DEFAULT_POPULATION_CSV = (
    PROJECT_DIR
    / "outputs"
    / "combined_population_summary"
    / "threshold_population_minute_features.csv"
)
DEFAULT_UNITS_CSV = (
    PROJECT_DIR
    / "outputs"
    / "combined_population_summary"
    / "threshold_units_used_summary.csv"
)
DEFAULT_OUT_DIR = PROJECT_DIR / "derived"

METRIC_RENAMES = {
    "firing_rate_hz": "firing_rate_hz",
    "average_amplitude_uv": "amplitude_ptp_uv",
    "cv2": "cv2",
    "peak_to_trough_ms": "peak_to_trough_ms",
}
METRIC_ORDER = tuple(METRIC_RENAMES.values())
SOURCE_MINUTE_META_COLUMNS = [
    "final_sample_id",
    "minute_start_datetime",
    "calendar_day",
    "clock_hour_of_day",
    "clock_minute_of_hour",
]
OUTPUT_MINUTE_META_COLUMNS = [
    "final_sample_id",
    "minute_start_datetime",
    "calendar_day",
    "clock_hour_of_day",
    "clock_minute_of_hour",
]


def log(message: str) -> None:
    print(f"[build_lightweight_feature_cache] {message}", flush=True)


def parse_pair_id(pair_id: str) -> tuple[int | None, str | None]:
    """Return sg channel and threshold-label text from a pair id."""
    parts = str(pair_id).split("_", 1)
    if not parts or not parts[0].startswith("sgch"):
        return None, None
    try:
        sg_ch = int(parts[0].replace("sgch", ""))
    except ValueError:
        sg_ch = None
    threshold_label = None
    if len(parts) > 1 and parts[1].startswith("thr") and parts[1].endswith("uV"):
        raw = parts[1][3:-2].replace("to", " to ").replace("p", ".")
        threshold_label = f"{raw} uV"
    return sg_ch, threshold_label


def clock_phase_rad(hour: pd.Series, minute: pd.Series | float = 0.0) -> pd.Series:
    return ((hour.astype(float) + np.asarray(minute, dtype=float) / 60.0) / 24.0) * (2.0 * math.pi)


def load_feature_dictionary(units_csv: Path) -> pd.DataFrame:
    units = pd.read_csv(units_csv)
    units = units.rename(
        columns={
            "final_group_key": "pair_id",
            "final_unit_id": "unit_id",
            "threshold_uv": "threshold_min_uv",
        }
    )
    rows = []
    for row in units.itertuples(index=False):
        pair_id = str(row.pair_id)
        sg_ch, threshold_label = parse_pair_id(pair_id)
        rows.append(
            {
                "unit_id": int(row.unit_id),
                "pair_id": pair_id,
                "sg_ch": int(getattr(row, "sg_ch", sg_ch if sg_ch is not None else -1)),
                "threshold_min_uv": float(row.threshold_min_uv),
                "threshold_label": threshold_label or "",
                "input_run_count": int(getattr(row, "input_run_count", 0)),
                "firing_rate_column": f"{pair_id}__firing_rate_hz",
                "amplitude_ptp_column": f"{pair_id}__average_amplitude_uv",
                "cv2_column": f"{pair_id}__cv2",
                "peak_to_trough_column": f"{pair_id}__peak_to_trough_ms",
            }
        )
    return pd.DataFrame(rows).sort_values(["sg_ch", "threshold_min_uv", "pair_id"]).reset_index(drop=True)


def write_minute_long(
    population_csv: Path,
    feature_dictionary: pd.DataFrame,
    out_csv: Path,
    *,
    chunksize: int,
) -> tuple[int, int]:
    first = True
    total_rows = 0
    chunks = 0
    usecols = list(SOURCE_MINUTE_META_COLUMNS)
    for row in feature_dictionary.itertuples(index=False):
        for source_metric in METRIC_RENAMES:
            usecols.append(f"{row.pair_id}__{source_metric}")
    usecols = [column for column in usecols if column in pd.read_csv(population_csv, nrows=0).columns]

    for chunk in pd.read_csv(population_csv, usecols=usecols, chunksize=chunksize):
        chunks += 1
        frames = []
        for unit in feature_dictionary.itertuples(index=False):
            metric_columns = {
                out_metric: f"{unit.pair_id}__{source_metric}"
                for source_metric, out_metric in METRIC_RENAMES.items()
            }
            if not all(column in chunk.columns for column in metric_columns.values()):
                continue
            frame = chunk[OUTPUT_MINUTE_META_COLUMNS].copy()
            frame.insert(0, "unit_id", int(unit.unit_id))
            frame.insert(1, "pair_id", str(unit.pair_id))
            frame.insert(2, "sg_ch", int(unit.sg_ch))
            frame.insert(3, "threshold_min_uv", float(unit.threshold_min_uv))
            frame.insert(4, "threshold_label", str(unit.threshold_label))
            for out_metric, source_column in metric_columns.items():
                frame[out_metric] = chunk[source_column].to_numpy()
            frames.append(frame)
        if not frames:
            continue
        out = pd.concat(frames, ignore_index=True)
        out["clock_phase_rad"] = clock_phase_rad(
            out["clock_hour_of_day"],
            out["clock_minute_of_hour"],
        )
        out["clock_phase_sin"] = np.sin(out["clock_phase_rad"])
        out["clock_phase_cos"] = np.cos(out["clock_phase_rad"])
        out.to_csv(out_csv, mode="w" if first else "a", header=first, index=False)
        first = False
        total_rows += len(out)
        log(f"wrote minute-long chunk {chunks}: {len(out):,} rows, total={total_rows:,}")
    return total_rows, chunks


def build_hour_long(minute_long_csv: Path, out_csv: Path, *, chunksize: int) -> int:
    group_columns = [
        "calendar_day",
        "clock_hour_of_day",
        "unit_id",
        "pair_id",
        "sg_ch",
        "threshold_min_uv",
        "threshold_label",
    ]
    accum: dict[tuple, dict[str, float]] = {}
    for chunk_index, chunk in enumerate(pd.read_csv(minute_long_csv, chunksize=chunksize), start=1):
        chunk["_minute_count"] = 1
        grouped = chunk.groupby(group_columns, dropna=False, sort=False)
        stats = grouped.agg(
            firing_rate_sum=("firing_rate_hz", "sum"),
            firing_rate_count=("firing_rate_hz", "count"),
            amplitude_sum=("amplitude_ptp_uv", "sum"),
            amplitude_count=("amplitude_ptp_uv", "count"),
            cv2_sum=("cv2", "sum"),
            cv2_count=("cv2", "count"),
            peak_to_trough_sum=("peak_to_trough_ms", "sum"),
            peak_to_trough_count=("peak_to_trough_ms", "count"),
            n_minute_rows=("_minute_count", "sum"),
        ).reset_index()
        for row in stats.itertuples(index=False):
            key = tuple(getattr(row, column) for column in group_columns)
            entry = accum.setdefault(
                key,
                {
                    "firing_rate_sum": 0.0,
                    "firing_rate_count": 0,
                    "amplitude_sum": 0.0,
                    "amplitude_count": 0,
                    "cv2_sum": 0.0,
                    "cv2_count": 0,
                    "peak_to_trough_sum": 0.0,
                    "peak_to_trough_count": 0,
                    "n_minute_rows": 0,
                },
            )
            for column in entry:
                entry[column] += getattr(row, column)
        log(f"aggregated minute-long chunk {chunk_index}")

    rows = []
    for key, entry in accum.items():
        row = dict(zip(group_columns, key))
        row["hour_start_datetime"] = f"{row['calendar_day']} {int(row['clock_hour_of_day']):02d}:00:00"
        row["clock_phase_rad"] = float((int(row["clock_hour_of_day"]) + 0.5) / 24.0 * 2.0 * math.pi)
        row["clock_phase_sin"] = math.sin(row["clock_phase_rad"])
        row["clock_phase_cos"] = math.cos(row["clock_phase_rad"])
        row["n_minute_rows"] = int(entry["n_minute_rows"])
        row["firing_rate_hz"] = entry["firing_rate_sum"] / entry["firing_rate_count"] if entry["firing_rate_count"] else np.nan
        row["amplitude_ptp_uv"] = entry["amplitude_sum"] / entry["amplitude_count"] if entry["amplitude_count"] else np.nan
        row["cv2"] = entry["cv2_sum"] / entry["cv2_count"] if entry["cv2_count"] else np.nan
        row["peak_to_trough_ms"] = (
            entry["peak_to_trough_sum"] / entry["peak_to_trough_count"]
            if entry["peak_to_trough_count"]
            else np.nan
        )
        rows.append(row)

    hour_long = pd.DataFrame(rows).sort_values(["calendar_day", "clock_hour_of_day", "sg_ch", "threshold_min_uv"])
    hour_long.to_csv(out_csv, index=False)
    return len(hour_long)


def build_hour_wide(hour_long_csv: Path, out_csv: Path) -> tuple[int, int]:
    table = pd.read_csv(hour_long_csv)
    id_columns = [
        "calendar_day",
        "clock_hour_of_day",
        "hour_start_datetime",
        "clock_phase_rad",
        "clock_phase_sin",
        "clock_phase_cos",
    ]
    metric_frames = []
    for metric in METRIC_ORDER:
        pivot = table.pivot_table(
            index=id_columns,
            columns="pair_id",
            values=metric,
            aggfunc="mean",
            sort=False,
        )
        pivot.columns = [f"{pair_id}__{metric}" for pair_id in pivot.columns]
        metric_frames.append(pivot)
    wide = pd.concat(metric_frames, axis=1).reset_index()
    wide = wide.sort_values(["calendar_day", "clock_hour_of_day"])
    wide.to_csv(out_csv, index=False)
    return wide.shape


def maybe_write_parquet(csv_path: Path) -> str | None:
    try:
        table = pd.read_csv(csv_path)
        parquet_path = csv_path.with_suffix(".parquet")
        table.to_parquet(parquet_path, index=False)
        return str(parquet_path)
    except Exception as exc:
        log(f"skipping parquet for {csv_path.name}: {exc}")
        return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--population-csv", type=Path, default=DEFAULT_POPULATION_CSV)
    parser.add_argument("--units-csv", type=Path, default=DEFAULT_UNITS_CSV)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--chunksize", type=int, default=1500)
    parser.add_argument("--parquet", action="store_true", help="Also write Parquet copies when pyarrow/fastparquet is available.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    start = time.perf_counter()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    population_csv = args.population_csv.resolve()
    units_csv = args.units_csv.resolve()

    feature_dictionary_csv = out_dir / "threshold_feature_dictionary.csv"
    minute_long_csv = out_dir / "threshold_minute_features_long.csv"
    hour_long_csv = out_dir / "threshold_hour_features_long.csv"
    hour_wide_csv = out_dir / "threshold_hour_matrix_wide.csv"
    manifest_json = out_dir / "threshold_lightweight_feature_cache_manifest.json"

    log(f"population input: {population_csv}")
    log(f"unit input: {units_csv}")
    feature_dictionary = load_feature_dictionary(units_csv)
    feature_dictionary.to_csv(feature_dictionary_csv, index=False)
    log(f"wrote feature dictionary: {feature_dictionary_csv} ({len(feature_dictionary):,} rows)")

    minute_rows, minute_chunks = write_minute_long(
        population_csv,
        feature_dictionary,
        minute_long_csv,
        chunksize=int(args.chunksize),
    )
    hour_rows = build_hour_long(minute_long_csv, hour_long_csv, chunksize=max(int(args.chunksize) * 50, 50_000))
    hour_shape = build_hour_wide(hour_long_csv, hour_wide_csv)

    parquet_outputs = []
    if args.parquet:
        for csv_path in [feature_dictionary_csv, minute_long_csv, hour_long_csv, hour_wide_csv]:
            parquet_path = maybe_write_parquet(csv_path)
            if parquet_path:
                parquet_outputs.append(parquet_path)

    csv_outputs = [feature_dictionary_csv, minute_long_csv, hour_long_csv, hour_wide_csv]
    manifest = {
        "created_at": pd.Timestamp.now().isoformat(),
        "population_csv": str(population_csv),
        "units_csv": str(units_csv),
        "out_dir": str(out_dir),
        "chunksize": int(args.chunksize),
        "n_units": int(len(feature_dictionary)),
        "minute_long_rows": int(minute_rows),
        "minute_chunks": int(minute_chunks),
        "hour_long_rows": int(hour_rows),
        "hour_wide_rows": int(hour_shape[0]),
        "hour_wide_columns": int(hour_shape[1]),
        "csv_outputs": [
            {
                "path": str(path),
                "bytes": int(path.stat().st_size),
            }
            for path in csv_outputs
        ],
        "parquet_outputs": parquet_outputs,
        "elapsed_seconds": float(time.perf_counter() - start),
    }
    manifest_json.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    log(f"wrote manifest: {manifest_json}")
    log(f"finished in {manifest['elapsed_seconds']:.1f} seconds")


if __name__ == "__main__":
    main()
